name: builder

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker
        run: |
          docker -v
        shell: bash