name: builder

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build img
        run: |
          docker build -t python-fastapi .
        shell: bash